crudNetMvc/Models/DB.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudNetMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crud1Entities1 : DbContext
    {
        public crud1Entities1()
            : base("name=crud1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persons> Persons { get; set; }
    }
}

crudNetMvc/Models/DB.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\HP\source\repos\crud-net-mvc\crud-net-mvc\Models\DB.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

crudNetMvc/Models/DB.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

crudNetMvc/Models/Persons.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudNetMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public int PersonID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}

crudNetMvc/Models/ViewModels/ListPersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace crudNetMvc.Models.ViewModels
{
    public class ListPersonViewModel
    {
        public int PersonID { get; set; }
        public string LastName  { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }


    }
}

crudNetMvc/Models/ViewModels/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace crudNetMvc.Models.ViewModels
{
    public class PersonViewModel
    {
        public int PersonID { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        [StringLength(20)]
        public string LastName { get; set; }
        [Required]
        [Display(Name = "Nombres")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Direccion")]
        public string Address { get; set; }
        [Required]
        [Display(Name = "Ciudad")]
        public string City { get; set; }
    }
}

crudNetMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace crudNetMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

crudNetMvc/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using crudNetMvc.Models;
using crudNetMvc.Models.ViewModels;

namespace crudNetMvc.Controllers
{
    public class PersonsController : Controller
    {
        // GET: Persons
        public ActionResult Index()
        {
            List<ListPersonViewModel> lst;
            using (crud1Entities1 db = new crud1Entities1()) {
                 lst = (from d in db.Persons
                           select new ListPersonViewModel
                           {
                               PersonID = d.PersonID,
                               LastName = d.LastName,
                               FirstName = d.FirstName,
                               Address = d.Address,
                               City = d.City
                           }).ToList();
                            
            }
                return View(lst);
        }

       

       
    

        public ActionResult UpdatePerson()
        {
            return View();
        }

        public ActionResult CreatePerson() {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePerson(PersonViewModel model) {
            try
            {
                if (ModelState.IsValid)
                {
                    using (crud1Entities1 db = new crud1Entities1())
                    {
                        var oPerson = new Persons();
                        oPerson.LastName = model.LastName;
                        oPerson.FirstName = model.FirstName;
                        oPerson.Address = model.Address;
                        oPerson.City = model.City;
                        db.Persons.Add(oPerson);
                        db.SaveChanges();
                    }
                }
                return Redirect("~/Persons/Index");

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult EditPerson( int PersonID)
        {
            PersonViewModel person = new PersonViewModel();
            using (crud1Entities1 db = new crud1Entities1()) {
                var oTable = db.Persons.Find(PersonID);
                person.FirstName = oTable.FirstName;
                person.LastName = oTable.LastName;
                person.Address = oTable.Address;
                person.City = oTable.City;
            }
            return View(person);
        }

        [HttpPost]
        public ActionResult EditPerson(PersonViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (crud1Entities1 db = new crud1Entities1())
                    {
                        var oPerson = db.Persons.Find(model.PersonID);
                        oPerson.LastName = model.LastName;
                        oPerson.FirstName = model.FirstName;
                        oPerson.Address = model.Address;
                        oPerson.City = model.City;
                        db.Entry(oPerson).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                return Redirect("~/Persons/Index");

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }


        public ActionResult DeletePerson(int PersonID)
        {
            PersonViewModel person = new PersonViewModel();
            using (crud1Entities1 db = new crud1Entities1())
            {
                var oTable = db.Persons.Find(PersonID);
                db.Persons.Remove(oTable);
                db.SaveChanges();
            }
            return Redirect("~/Persons/");
        }

    }
}

crudNetMvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

crudNetMvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

crudNetMvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

crudNetMvc/Views/Persons/CreatePerson.cshtml
@model crudNetMvc.Models.ViewModels.PersonViewModel

@{
    ViewBag.Title = "Crear Persona";
}


@using (Html.BeginForm("CreatePerson", "Persons", FormMethod.Post))
{
 
    <h2>@ViewBag.Title </h2>
    
    <div class="row">
        <div class="col-md-12">
            <div>
                <div>
                    @Html.LabelFor(d => d.FirstName)
                    @Html.TextBoxFor(d => d.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.FirstName, null, new { @class = "danger" })
                </div>
            </div>
       
            @Html.LabelFor(d => d.LastName)
            @Html.ValidationMessageFor(d => d.LastName)
            @Html.TextBoxFor(d => d.LastName, new { @class = "form-control" })

            @Html.LabelFor(d => d.Address)
            @Html.TextBoxFor(d => d.Address, new { @class = "form-control" })

            @Html.LabelFor(d => d.City)
            @Html.TextBoxFor(d => d.City, new { @class = "form-control" })

        </div>
        <div class="form-group">
            <div class="col-md-offset-1 col-md-2"  style="text-align : right; padding:5px">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

crudNetMvc/Views/Persons/EditPerson.cshtml
@model crudNetMvc.Models.ViewModels.PersonViewModel

@{
    ViewBag.Title = "EditPerson";
}

<h2>EditPerson</h2>

@using (Html.BeginForm("EditPerson", "Persons", FormMethod.Post))
{
   
    <div class="form-horizontal">
        <h4>PersonViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
        @Html.HiddenFor(d => d.PersonID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

crudNetMvc/Views/Persons/Index.cshtml
@model List <crudNetMvc.Models.ViewModels.ListPersonViewModel>

@{
    ViewBag.Title = "Listar Clientes";
}

    <h2>@ViewBag.Title</h2>

    <div class="row" style="text-align:right;padding:7px">
        <a href="~/Persons/CreatePerson" class="btn btn-primary" >Nuevo Cliente</a>
    </div>
<div class="row">
    <div>
        <table class="table">
            <tr>
                <th>
                    #
                </th>
                <th>
                    Nombre
                </th>
                <th>
                    Apellido
                </th>
                <th>
                    Ciudad
                </th>
            </tr>
            @foreach (var oElemento in Model)
            {
        <tr>
            <td>@oElemento.PersonID</td>
            <td>@oElemento.FirstName</td>
            <td>@oElemento.LastName</td>
            <td>@oElemento.City</td>
            <td>
                <a class="btn btn-default" href=@Url.Action("EditPerson", "Persons", new { PersonID = @oElemento.PersonID })>Editar</a>
                <a class="btn btn-danger" href=@Url.Action("DeletePerson", "Persons", new { PersonID = @oElemento.PersonID })>Eliminar</a>
            </td>
        </tr>
            }
        </table>
    </div>

</div>

crudNetMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>